Repository Imsurajkr/Firsttimeronly, pull requests merged in 2020-10, with the labels that each got.

#14 updated compare arr code by jarvis
  java/compareArr.java
  js/compareArr.js
  js/helloWorld.js
  js/palin.js
Labels: Hacktoberfest-accepted, hacktoberfest

#15 palin solution 2
  js/palin1.js
Labels: Hacktoberfest-accepted, hacktoberfest

#16 palindrom solution more fast and in less space complexity
  js/palin2.js
Labels: Hacktoberfest-accepted, documentation, enhancement, hacktoberfest

#17 roman no coverter solution in js
  js/romanConverter.js
Labels: Hacktoberfest-accepted, documentation, hacktoberfest

#18 Basic STL vector program
  c++/stl:vector
Labels: Hacktoberfest-accepted, hacktoberfest

#19 Updated java palindrome code
  java/palindrome.java
Labels: Hacktoberfest-accepted, hacktoberfest

#20 updated prime number codes
  java/prmieNumber.java
Labels: Hacktoberfest-accepted, hacktoberfest

#22 updated fibonnaci series
  java/fibonacci.java
Labels: Hacktoberfest-accepted, hacktoberfest

#21 Create railfencecipherdecoder.py
  c++/railfencecipherdecoder.py
Labels: Hacktoberfest-accepted, hacktoberfest

#23 updated GCD in java
  java/gcd.java
Labels: Hacktoberfest-accepted, hacktoberfest

#24 fibonacci series
  c++/fibonacci_series.cpp
Labels: Hacktoberfest-accepted, hacktoberfest

#25 Interference added
  java/interference.java
Labels: Hacktoberfest-accepted, hacktoberfest

#26 new file added
  HTML/new.html
Labels: Hacktoberfest-accepted, hacktoberfest

#27 pyramid pattern
  c/pyramid.c
Labels: Hacktoberfest-accepted, hacktoberfest

#28 PATTERN CODE
  java/Pattern2.java
Labels: Hacktoberfest-accepted, hacktoberfest

#29 EXCEPTION HANDLING
  java/abc.java
Labels: Hacktoberfest-accepted, hacktoberfest

#30 factorial
  java/fact.java
  java/factorial.java
Labels: Hacktoberfest-accepted, hacktoberfest

#31 filehandling.c++
  c/filehandling.c++
Labels: Hacktoberfest-accepted, hacktoberfest

#32 RectangleArea file added
  js/rectangleArea.js
Labels: Hacktoberfest-accepted, hacktoberfest

#33 FindTable
  java/table.java
Labels: Hacktoberfest-accepted, hacktoberfest

#34 lambda function in java
  java/Program27.java
  java/lambda.java
Labels: Hacktoberfest-accepted, hacktoberfest

#35 Delete Program27.java
  java/Program27.java
Labels: Hacktoberfest-accepted, hacktoberfest

#36 program41
  java/Program41.java
Labels: Hacktoberfest-accepted, hacktoberfest

#37 Number abbreviation function added
  js/abbreviateNumber.js
Labels: Hacktoberfest-accepted, hacktoberfest

#38 getProperty function added
  js/getProperty.js
Labels: Hacktoberfest-accepted, hacktoberfest
